"use client"
import { useEffect, useState } from "react"

type Entry = { name: string; amount: string; renewal: string }
const defaults: Entry[] = ["Hosting", "Database & storage", "AI tools", "Email & WhatsApp", "Domain"].map(name=>({name,amount:"",renewal:""}))
export function CostPlanner({userId}: {userId: string}) {
  const key = `whitec-cost-plan-v1:${userId}`
  const [entries,setEntries] = useState<Entry[]>(defaults)
  const [budget,setBudget] = useState("")
  const [ready,setReady] = useState(false)
  const [message,setMessage] = useState("")
  useEffect(()=>{try { const raw=localStorage.getItem(key); if(raw) {const saved=JSON.parse(raw); if(Array.isArray(saved.entries)&&saved.entries.length===5&&saved.entries.every((e:Entry)=>typeof e.name==="string"&&typeof e.amount==="string"&&typeof e.renewal==="string")&&typeof saved.budget==="string") {setEntries(saved.entries);setBudget(saved.budget)}}} catch {setMessage("Saved estimates could not be read. You can enter them again.")} setReady(true)},[key])
  const total=entries.reduce((n,e)=>n+(Math.max(0,Number(e.amount))||0),0)
  const cap=Math.max(0,Number(budget))||0
  function save() {try {localStorage.setItem(key,JSON.stringify({entries,budget}));setMessage("Saved on this browser.")} catch {setMessage("Could not save. Browser storage may be unavailable.")}}
  function download() {const blob=new Blob([JSON.stringify({currency:"INR",entries,budget,updatedAt:new Date().toISOString()},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="whitec-cost-plan.json";a.click();URL.revokeObjectURL(url)}
  return <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-5"><div><h2 className="text-lg font-semibold">Your monthly budget</h2><p className="mt-1 text-sm text-slate-500">Enter estimates in ₹. These are your notes, not connected invoices.</p></div><div><span className="text-2xl font-semibold">₹{total.toLocaleString("en-IN")}</span><span className="ml-2 text-xs text-slate-500">entered / month</span></div></div><fieldset disabled={!ready} className="mt-6"><div className="grid gap-4 md:grid-cols-5">{entries.map((entry,i)=><div key={entry.name} className="rounded-xl bg-slate-50 p-4"><label className="text-sm font-medium">{entry.name}<input aria-label={`${entry.name} monthly amount`} type="number" min="0" max="10000000" value={entry.amount} placeholder="Not entered" onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,amount:e.target.value}:v))} className="mt-3 w-full rounded-lg border bg-white p-2 text-sm" /></label><label className="mt-3 block text-xs text-slate-500">Next renewal<input aria-label={`${entry.name} renewal`} type="date" value={entry.renewal} onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,renewal:e.target.value}:v))} className="mt-2 w-full min-w-0 rounded-lg border bg-white p-2 text-xs" /></label></div>)}</div><div className="mt-5 flex flex-wrap items-end gap-4"><label className="text-xs text-slate-600">Monthly spending target (₹)<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} className="mt-1 block rounded-lg border p-2 text-sm" /></label><button onClick={save} className="rounded-lg bg-[#173e3b] px-5 py-2.5 text-sm text-white">Save estimates</button><button onClick={download} className="rounded-lg border px-5 py-2.5 text-sm">Export cost plan</button>{cap>0&&<p className={`text-sm ${total>cap?"text-red-700":"text-teal-700"}`}>{total>cap?`₹${(total-cap).toLocaleString("en-IN")} over target`:`₹${(cap-total).toLocaleString("en-IN")} remaining`}</p>}</div></fieldset><p role="status" className="mt-3 text-sm text-teal-700">{message}</p><p className="mt-2 text-xs text-slate-500">Stored only in this browser; export to keep a copy or move devices. No subscription changes are made here.</p></section>
}
